language: groovy
sudo: false
before_install:
  - echo Before install...
  - echo Updating submodules...
  - git submodule update --init --recursive
  - echo Setting up workspace...
  - chmod +x gradlew
  - ls -a -l -h --color
  - echo Downloading Gradle....
  - ./gradlew
  - ./gradlew -version
install:
  - echo Install...
  - ./gradlew assemble
before_script:
  - echo Starting building process...
  - echo Before script...
  - echo Printing dependencies...
  - ./gradlew dependencies
script:
  - echo Script...
  - ./gradlew check --info
after_success:
  - echo Build successful
  - echo Now building the artifacts
  - ./gradlew build --info
  - echo Deploying artifact
  - echo == Insert here artifact deploy ==
after_failure:
  - echo Build failed
  - echo See the log for errors
  - echo Deploying build log...
  - echo == Insert here log deploy ==
after_script:
  - echo After script...
  - echo == Insert cleanup if needed ==
  - echo Build terminated.
notifications:
  email:
    recipients:
      - sir.karati@outlook.com
#      - bartek.bok@gmail.com
    on_success: change
    on_failure: always
  slack:
    on_success: always
    on_failure: always