language: groovy
sudo: false
notifications:
  email:
    recipients:
      - sir.karati@outlook.com
    on_success: change
    on_failure: always
  slack:
    on_success: always
    on_failure: always